In [99]:
import numpy as np
import pandas as pd

In [100]:
data = pd.read_csv('stock_data.csv')
data

Text  Sentiment
0     Kickers on my watchlist XIDE TIT SOQ PNK CPW B...          1
1     user: AAP MOVIE. 55% return for the FEA/GEED i...          1
2     user I'd be afraid to short AMZN - they are lo...          1
3                                     MNTA Over 12.00            1
4                                      OI  Over 21.37            1
...                                                 ...        ...
5786  Industry body CII said #discoms are likely to ...         -1
5787  #Gold prices slip below Rs 46,000 as #investor...         -1
5788  Workers at Bajaj Auto have agreed to a 10% wag...          1
5789  #Sharemarket LIVE: Sensex off day’s high, up 6...          1
5790  #Sensex, #Nifty climb off day's highs, still u...          1

[5791 rows x 2 columns]

In [101]:
X_values = data['Text']
Y_values = data['Sentiment']
print(X_values, Y_values)

0       Kickers on my watchlist XIDE TIT SOQ PNK CPW B...
1       user: AAP MOVIE. 55% return for the FEA/GEED i...
2       user I'd be afraid to short AMZN - they are lo...
3                                       MNTA Over 12.00  
4                                        OI  Over 21.37  
                              ...                        
5786    Industry body CII said #discoms are likely to ...
5787    #Gold prices slip below Rs 46,000 as #investor...
5788    Workers at Bajaj Auto have agreed to a 10% wag...
5789    #Sharemarket LIVE: Sensex off day’s high, up 6...
5790    #Sensex, #Nifty climb off day's highs, still u...
Name: Text, Length: 5791, dtype: object 0       1
1       1
2       1
3       1
4       1
       ..
5786   -1
5787   -1
5788    1
5789    1
5790    1
Name: Sentiment, Length: 5791, dtype: int64


In [102]:
data['Sentiment'] = data['Sentiment'].replace(-1, 0)
data['Sentiment'].value_counts()

1    3685
0    2106
Name: Sentiment, dtype: int64

In [103]:
import spacy
import re
nlp = spacy.load('en_core_web_sm')

In [104]:
processed_data = []
pattern = ' +'
replacement = ' '
for text in X_values:
    doc = nlp(text)
    processed_text = []
    for token in doc:
        if token.is_stop == False:
            if token.is_punct == False:
                token = re.sub(pattern, replacement, str(token.lemma_.lower()))
                processed_text.append(token)
    # processed_text = re.sub(pattern, replacement, processed_text)
    processed_data.append(' '.join(processed_text))
X_values = processed_data
X_values    

['kicker watchlist xide tit soq pnk cpw bpz aj   trade method 1 method 2 prev post',
 'user aap movie 55 return fea geed indicator 15 trade year   awesome  ',
 'user afraid short amzn look like near monopoly ebooks infrastructure service',
 'mnta 12.00  ',
 'oi   21.37  ',
 'pgnx   3.04  ',
 'aap user current downtrend break short term correction med term downtrend',
 'monday relative weakness nyx win tie tap ice int bmc aon c chk biib  ',
 'goog ower trend line channel test volume support  ',
 'aap watch tomorrow ong entry',
 'assume fcx open tomorrow 34.25 trigger buy like setup  ',
 'worry expect market rally usually exact opposite happen time shall soon bac spx jpm',
 'aap gamco arry haverty apple extremely cheap   great video',
 'user maykiljil post   agree msft go high possibly north 30',
 'momentum come etfc break ma200 resistance solid volume friday ong set  ',
 'ha hit 35.65 mean resume target 42 level  ',
 'user gameplan shoot today like   trend break c+h break oc weekly tren

In [105]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectors for all documents
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(data['Text'])
data['tfidf'] = list(tfidf_matrix.toarray())
data.head()

Text  Sentiment  \
0  Kickers on my watchlist XIDE TIT SOQ PNK CPW B...          1   
1  user: AAP MOVIE. 55% return for the FEA/GEED i...          1   
2  user I'd be afraid to short AMZN - they are lo...          1   
3                                  MNTA Over 12.00            1   
4                                   OI  Over 21.37            1   

                                               tfidf  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.4218558036868526, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [106]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data.tfidf.values,
    data.Sentiment,
    test_size=0.2,
    random_state=2022
)

In [107]:
X_train

array([array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]), ...,
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.])], dtype=object)

In [108]:
X_train_2d = np.stack(X_train)
X_test_2d = np.stack(X_test)

In [109]:
X_test_2d

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [110]:
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

#1. creating a KNN model object
clf = KNeighborsClassifier(n_neighbors = 10, metric = 'euclidean')

#2. fit with all_train_embeddings and y_train
clf.fit(X_train_2d, y_train)

#3. get the predictions for all_test_embeddings and store it in y_pred
y_pred = clf.predict(X_test_2d)

#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.64      0.64       416
           1       0.80      0.81      0.80       743

    accuracy                           0.75      1159
   macro avg       0.72      0.72      0.72      1159
weighted avg       0.75      0.75      0.75      1159



In [111]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
scaled_train_embed = scaler.fit_transform(X_train_2d)
scaled_test_embed = scaler.transform(X_test_2d)


clf = MultinomialNB()
clf.fit(scaled_train_embed, y_train)

y_pred = clf.predict(scaled_test_embed)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.49      0.57       416
           1       0.75      0.87      0.81       743

    accuracy                           0.73      1159
   macro avg       0.72      0.68      0.69      1159
weighted avg       0.73      0.73      0.72      1159



In [112]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Create an instance of the model
logistic_regression = LogisticRegression()


# Fit the model
logistic_regression.fit(X_train_2d, y_train)

# Predict the labels
y_pred = logistic_regression.predict(X_test_2d)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

# Calculate the confusion matrix
print(classification_report(y_test, y_pred))

Accuracy:  0.7834339948231234
              precision    recall  f1-score   support

           0       0.77      0.56      0.65       416
           1       0.79      0.91      0.84       743

    accuracy                           0.78      1159
   macro avg       0.78      0.74      0.75      1159
weighted avg       0.78      0.78      0.77      1159



In [113]:
# Save the Model
import joblib

joblib.dump(logistic_regression, 'model.joblib')

['model.joblib']

In [114]:
joblib.dump(tfidf_vectorizer, 'tfidf_vectorizer.joblib')

['tfidf_vectorizer.joblib']